=== PavelKastrykin/TestBankParser/src/Bank.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.pavel.com/bank"
        xmlns:bnc="http://www.pavel.com/bank">

    <simpleType name="TypeOfAccount">
        <restriction base="string">
            <enumeration value="deposit"/>
            <enumeration value="demand"/>
            <enumeration value="checking"/>
            <enumeration value="saving"/>
            <enumeration value="accumulating"/>
            <enumeration value="metal"/>
        </restriction>
    </simpleType>

    <complexType name="account">
        <sequence>
            <element name="nameOfBank">
                <simpleType>
                    <restriction base="string">
                        <minLength value="1"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="country">
                <simpleType>
                    <restriction base="string">
                        <minLength value="1"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="typeOfAccount" type="bnc:TypeOfAccount"/>

            <element name="depositor">
                <simpleType>
                    <restriction base="string">
                        <minLength value="1"/>
                        <maxLength value="30"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="accountID">
                <simpleType>
                    <restriction base="long">
                        <pattern value="\d{13}"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="amount">
                <simpleType>
                    <restriction base="double">
                        <minInclusive value="0"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="annualProfit">
                <simpleType>
                    <restriction base="float">
                        <minInclusive value="0"/>
                    </restriction>
                </simpleType>
            </element>

            <element name="term">
                <simpleType>
                    <restriction base="float">
                        <minExclusive value="0"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>

        <attribute name="IBAN" type="bnc:Iban" use="required"/>

    </complexType>

    <element name="bank">
        <complexType>
            <sequence>
                <element name = "account" type = "bnc:account"
                             minOccurs="1" maxOccurs = "unbounded"/>
            </sequence>
        </complexType>
    </element>

    <simpleType name="Iban">
        <restriction base="ID">
            <pattern value="[A-Za-z]{2}[A-Za-z0-9\s_-]+"/>
        </restriction>
    </simpleType>

</schema>

=== PavelKastrykin/TestBankParser/src/Bank.xml
<?xml version="1.0" encoding="UTF-8"?>
<bnc:bank xmlns:bnc="http://www.pavel.com/bank"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.pavel.com/bank Bank.xsd">

    <account IBAN = "US29NWBK60161331926819" >
        <nameOfBank>Bank of America</nameOfBank>
        <country>USA</country>
        <typeOfAccount>deposit</typeOfAccount>
        <depositor>Michael Douglas</depositor>
        <accountID>1325468749562</accountID>
        <amount>10000000</amount>
        <annualProfit>5</annualProfit>
        <term>20</term>
    </account>
    <account IBAN = "DE89370400440532013000" >
        <nameOfBank>Commerzbank</nameOfBank>
        <country>Germany</country>
        <typeOfAccount>demand</typeOfAccount>
        <depositor>Hansi Kuersch</depositor>
        <accountID>1523614785921</accountID>
        <amount>250000</amount>
        <annualProfit>4.5</annualProfit>
        <term>7</term>
    </account>
    <account IBAN = "KZ75125KZT1001300335" >
        <nameOfBank>KAZKOM</nameOfBank>
        <country>Kazakhstan</country>
        <typeOfAccount>checking</typeOfAccount>
        <depositor>Rustam Nabirov</depositor>
        <accountID>3251489647513</accountID>
        <amount>7500000</amount>
        <annualProfit>13</annualProfit>
        <term>12</term>
    </account>
    <account IBAN = "NL91ABNA0417164300" >
        <nameOfBank>ABN AMRO</nameOfBank>
        <country>Netherlands</country>
        <typeOfAccount>saving</typeOfAccount>
        <depositor>Floor Jansen</depositor>
        <accountID>1532486985211</accountID>
        <amount>50000</amount>
        <annualProfit>8</annualProfit>
        <term>5</term>
    </account>
    <account IBAN = "UA853996220000000260012335661" >
        <nameOfBank>Privatbank</nameOfBank>
        <country>Ukraine</country>
        <typeOfAccount>accumulating</typeOfAccount>
        <depositor>Piotr Poroshenko</depositor>
        <accountID>2564895214783</accountID>
        <amount>173000</amount>
        <annualProfit>22</annualProfit>
        <term>3</term>
    </account>
    <account IBAN = "SE4550000000058398257466" >
        <nameOfBank>Swedbank</nameOfBank>
        <country>Sweden</country>
        <typeOfAccount>metal</typeOfAccount>
        <depositor>Bjorn Borg</depositor>
        <accountID>1356954785236</accountID>
        <amount>330000</amount>
        <annualProfit>7.5</annualProfit>
        <term>16</term>
    </account>
</bnc:bank>
